[package]
name = "chatserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.17", features = ["ws"] }
axum-macros = "*"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0.71"
uuid = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "1.0.96"
tokio-stream = { version = "0.1.14", features = ["sync"] }
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
sqlx = { version = "0.7.3", features = ["postgres"] }
